<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Setting up reports and Test is getting ready]]>
    </line>
    <line>
      <![CDATA[Setting Done-Test can be started]]>
    </line>
    <line>
      <![CDATA[Trying to start browser and Getting application ready]]>
    </line>
    <line>
      <![CDATA[Browser and  Application is up and running]]>
    </line>
    <line>
      <![CDATA[Test is about to end]]>
    </line>
    <line>
      <![CDATA[Test completed >>>> Reports Generated]]>
    </line>
    <line>
      <![CDATA[Test is about to end]]>
    </line>
    <line>
      <![CDATA[Test completed >>>> Reports Generated]]>
    </line>
  </reporter-output>
  <suite started-at="2023-12-06T18:26:37 IST" name="Default suite" finished-at="2023-12-06T18:27:43 IST" duration-ms="66121">
    <groups>
    </groups>
    <test started-at="2023-12-06T18:26:37 IST" name="Default test" finished-at="2023-12-06T18:27:43 IST" duration-ms="66121">
      <class name="com.learnautomation.testcases.DataDrivenTest">
        <test-method is-config="true" signature="setUpSuite()[pri:0, instance:com.learnautomation.testcases.DataDrivenTest@1165b38]" started-at="2023-12-06T18:26:37 IST" name="setUpSuite" finished-at="2023-12-06T18:26:37 IST" duration-ms="224" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Setting up reports and Test is getting ready]]>
            </line>
            <line>
              <![CDATA[Setting Done-Test can be started]]>
            </line>
          </reporter-output>
        </test-method> <!-- setUpSuite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.learnautomation.testcases.DataDrivenTest@1165b38]" started-at="2023-12-06T18:26:37 IST" name="setUp" finished-at="2023-12-06T18:27:29 IST" duration-ms="52119" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Trying to start browser and Getting application ready]]>
            </line>
            <line>
              <![CDATA[Browser and  Application is up and running]]>
            </line>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginDDT(java.lang.String,java.lang.String)[pri:1, instance:com.learnautomation.testcases.DataDrivenTest@1165b38]" started-at="2023-12-06T18:27:30 IST" name="loginDDT" data-provider="LoginData" finished-at="2023-12-06T18:27:36 IST" duration-ms="5736" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr515502]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ydYhEqA]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.learnautomation.testcases.DataDrivenTest.loginDDT(DataDrivenTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDDT -->
        <test-method is-config="true" signature="tearDownMethod(org.testng.ITestResult)[pri:0, instance:com.learnautomation.testcases.DataDrivenTest@1165b38]" started-at="2023-12-06T18:27:36 IST" name="tearDownMethod" finished-at="2023-12-06T18:27:37 IST" duration-ms="869" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginDDT status=FAILURE method=DataDrivenTest.loginDDT(java.lang.String,java.lang.String)[pri:1, instance:com.learnautomation.testcases.DataDrivenTest@1165b38] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test is about to end]]>
            </line>
            <line>
              <![CDATA[Test completed >>>> Reports Generated]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method signature="loginDDT(java.lang.String,java.lang.String)[pri:1, instance:com.learnautomation.testcases.DataDrivenTest@1165b38]" started-at="2023-12-06T18:27:37 IST" name="loginDDT" data-provider="LoginData" finished-at="2023-12-06T18:27:42 IST" duration-ms="5153" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.learnautomation.testcases.DataDrivenTest.loginDDT(DataDrivenTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDDT -->
        <test-method is-config="true" signature="tearDownMethod(org.testng.ITestResult)[pri:0, instance:com.learnautomation.testcases.DataDrivenTest@1165b38]" started-at="2023-12-06T18:27:42 IST" name="tearDownMethod" finished-at="2023-12-06T18:27:42 IST" duration-ms="309" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginDDT status=FAILURE method=DataDrivenTest.loginDDT(java.lang.String,java.lang.String)[pri:1, instance:com.learnautomation.testcases.DataDrivenTest@1165b38] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test is about to end]]>
            </line>
            <line>
              <![CDATA[Test completed >>>> Reports Generated]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.learnautomation.testcases.DataDrivenTest@1165b38]" started-at="2023-12-06T18:27:42 IST" name="tearDown" finished-at="2023-12-06T18:27:43 IST" duration-ms="509" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.learnautomation.testcases.DataDrivenTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
